---

- name: Run file commands
  gather_facts: false
  hosts: all

  tasks:
    - name: Create a directory
      file:
        path: /home/grojas/myfolder
        state: directory
        owner: grojas
        group: grojas


    - name: Delete sample-template.bak file
      file:
        path: /home/user/sample-template.bak
        state: absent

