---

- name: Run file commands
  gather_facts: false
  hosts: all

  tasks:
    - name: Create a directory
      file:
        path: /home/grojas/myfolder2
        state: directory
        owner: grojas
        group: grojas

    - name: Create a directory
      file:
        shell: 'touch sample-template.txt'
        args:
          chdir: /home/grojas/myfolder2